return {
  -- {
  --   "MunifTanjim/prettier.nvim",
  --   dependencies = {
  --     { "neovim/nvim-lspconfig" },
  --     { "jose-elias-alvarez/null-ls.nvim" },
  --   },
  --   config = function()
  --     -- 格式化
  --     local prettier = require("prettier")
  --
  --     prettier.setup({
  --       bin = "prettier", -- or `'prettierd'` (v0.23.3+)
  --       filetypes = {
  --         "css",
  --         "graphql",
  --         "html",
  --         "javascript",
  --         "javascriptreact",
  --         "json",
  --         "less",
  --         "markdown",
  --         "scss",
  --         "typescript",
  --         "typescriptreact",
  --         "yaml",
  --       },
  --       cli_options = {
  --         single_quote = false,
  --         tab_width = 4,
  --         print_width = 120,
  --       },
  --     })
  --   end,
  -- },
}
